# Generated by Django 4.2.21 on 2025-05-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Mã Lớp học')),
                ('class_name', models.CharField(max_length=40, verbose_name='Tên lớp học')),
                ('class_type', models.CharField(max_length=1, verbose_name='Loại lớp')),
                ('room', models.CharField(max_length=15, verbose_name='Phòng học')),
                ('khai_giang_date', models.DateField(verbose_name='Ngày khai giảng')),
                ('ket_thuc_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('si_so', models.IntegerField(verbose_name='Sĩ số tối đa')),
                ('price', models.IntegerField(verbose_name='Học phí')),
            ],
            options={
                'verbose_name': 'Lớp Học',
                'verbose_name_plural': 'Lớp Học',
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Mã Học Viên')),
                ('full_name', models.CharField(max_length=40, verbose_name='Họ và Tên')),
                ('gender', models.CharField(max_length=1, verbose_name='Giới tính')),
                ('birth_day', models.DateField(verbose_name='Ngày sinh')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('sdt', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=30, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Học Viên',
                'verbose_name_plural': 'Học Viên',
                'db_table': 'HocVien',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Mã Nhân Viên')),
                ('full_name', models.CharField(max_length=40, verbose_name='Họ và Tên')),
                ('gender', models.CharField(max_length=1, verbose_name='Giới tính')),
                ('birth_day', models.DateField(verbose_name='Ngày sinh')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('sdt', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=30, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Nhân Viên',
                'db_table': 'NhanVien',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Mã Giáo Viên')),
                ('full_name', models.CharField(max_length=40, verbose_name='Họ và Tên')),
                ('gender', models.CharField(max_length=1, verbose_name='Giới tính')),
                ('birth_day', models.DateField(verbose_name='Ngày sinh')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('sdt', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=30, verbose_name='Địa chỉ')),
                ('trinh_do', models.CharField(max_length=6, verbose_name='Trình độ')),
            ],
            options={
                'verbose_name': 'Giáo Viên',
                'verbose_name_plural': 'Giáo Viên',
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Mã Lịch học')),
                ('day', models.CharField(max_length=20, verbose_name='Ngày trong tuần/Buổi học')),
                ('start_time', models.TimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Thời gian kết thúc')),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.class', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Lịch Học',
                'verbose_name_plural': 'Lịch Học',
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id_feedback', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Mã Feedback')),
                ('class_rate', models.FloatField(blank=True, null=True, verbose_name='Đánh giá lớp học')),
                ('teacher_rate', models.FloatField(blank=True, null=True, verbose_name='Đánh giá giáo viên')),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Lớp học')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.hocvien', verbose_name='Học viên')),
                ('teacher', models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'Feedback',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, db_column='MaNV', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nhanvien', verbose_name='Nhân viên quản lý'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='Giáo viên'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id_attend', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Mã Điểm danh')),
                ('attendance_date', models.DateField(verbose_name='Ngày điểm danh')),
                ('status', models.CharField(max_length=15, verbose_name='Trạng thái')),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Lớp học')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.hocvien', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Điểm Danh',
                'verbose_name_plural': 'Điểm Danh',
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Ngày đăng ký')),
                ('minitest1', models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 1')),
                ('minitest2', models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 2')),
                ('minitest3', models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 3')),
                ('minitest4', models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 4')),
                ('midterm', models.FloatField(blank=True, null=True, verbose_name='Điểm giữa kỳ')),
                ('final', models.FloatField(blank=True, null=True, verbose_name='Điểm cuối kỳ')),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Lớp học')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.hocvien', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Đăng Ký Học',
                'verbose_name_plural': 'Đăng Ký Học',
                'db_table': 'Enrollments',
                'unique_together': {('student', 'class_obj')},
            },
        ),
    ]
