# Generated by Django 4.2.21 on 2025-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='midterm1',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='midterm2',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='midterm3',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='midterm4',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='midterm',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm giữa kỳ'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='minitest1',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 1'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='minitest2',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 2'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='minitest3',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 3'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='minitest4',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm minitest 4'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
