# Generated by Django 5.2 on 2025-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='si_so',
            field=models.IntegerField(default=0, verbose_name='Sĩ số hiện tại'),
        ),
    ]
