# Generated by Django 4.2.21 on 2025-05-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='trinh_do',
            field=models.CharField(default='Cử nhân', max_length=10, verbose_name='Trình độ'),
        ),
    ]
