# Generated by Django 5.2 on 2025-06-03 19:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clazz_si_so'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_obj',
            field=models.OneToOneField(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.clazz', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('2', 'Thứ 2'), ('3', 'Thứ 3'), ('4', 'Thứ 4'), ('5', 'Thứ 5'), ('6', 'Thứ 6'), ('7', 'Thứ 7'), ('CN', 'Chủ nhật')], max_length=2), size=3, verbose_name='Các ngày trong tuần'),
        ),
    ]
