# Generated by Django 4.2.21 on 2025-05-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teacher_trinh_do'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='clazz',
        ),
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='enrollments',
        ),
        migrations.RenameModel(
            old_name='HocVien',
            new_name='hoc_vien',
        ),
        migrations.RenameModel(
            old_name='NhanVien',
            new_name='nhan_vien',
        ),
        migrations.AlterModelTable(
            name='clazz',
            table='clazz',
        ),
        migrations.AlterModelTable(
            name='enrollments',
            table='enrollments',
        ),
        migrations.AlterModelTable(
            name='hoc_vien',
            table='hoc_vien',
        ),
        migrations.AlterModelTable(
            name='nhan_vien',
            table='nhan_vien',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
