# Generated by Django 4.2.21 on 2025-05-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_enrollment_midterm1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='Attendance',
        ),
        migrations.AlterModelTable(
            name='class',
            table='Class',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='Enrollments',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
        migrations.AlterModelTable(
            name='hocvien',
            table='HocVien',
        ),
        migrations.AlterModelTable(
            name='nhanvien',
            table='NhanVien',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='Schedule',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
