# Generated by Django 4.2.21 on 2025-05-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_class_clazz_rename_enrollment_enrollments_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
