# Generated by Django 4.2.21 on 2025-05-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
    ]
