# Generated by Django 4.2.21 on 2025-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm cuối kỳ'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='midterm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm giữa kỳ'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='minitest1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm minitest 1'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='minitest2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm minitest 2'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='minitest3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm minitest 3'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='minitest4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm minitest 4'),
        ),
    ]
